# Generated by Django 5.1.1 on 2024-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_contacts_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
