# Generated by Django 5.1.1 on 2024-10-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_comment_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='page_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.event'),
            preserve_default=False,
        ),
    ]
